In [1]:
from google.cloud import bigquery

# BigQuery vers le projet
client = bigquery.Client(project="wagon-bootcamp-501621")

#le nombre de lignes et la liste des colonnes ( afficher)
table = client.get_table("wagon-bootcamp-501621.staging.catnat_staging")
print("Nombre de lignes :", table.num_rows)
for col in table.schema:
    print(col.name, "-", col.field_type)

Nombre de lignes : 247140
id_gaspar - STRING
code_commune - STRING
libelle_commune - STRING
num_risque_jo - STRING
lib_risque_jo - STRING
date_debut - DATE
date_fin - DATE
date_signature_arrete - DATE
date_publication_jo - DATE
date_modification - DATE

In [2]:
# Afficher 5 lignes d'exemple
df = client.query("""
    SELECT * FROM `wagon-bootcamp-501621.staging.catnat_staging` LIMIT 5
""").to_dataframe()
df

/Users/asmaammouri/code/Asma-Iam/hydraxai-france/.venv/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2128: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,id_gaspar,code_commune,libelle_commune,num_risque_jo,lib_risque_jo,date_debut,date_fin,date_signature_arrete,date_publication_jo,date_modification
0,NOR19821214,43234,saugues,ICB,inondations et/ou coulees de boue,1982-08-15,1982-08-15,1982-12-14,1982-12-18,2022-05-20
1,NOR19821214,43224,sainte-sigolene,ICB,inondations et/ou coulees de boue,1982-08-15,1982-08-15,1982-12-14,1982-12-18,2022-05-20
2,NOR19820921,69009,anse,ICB,inondations et/ou coulees de boue,1982-08-16,1982-08-16,1982-09-21,1982-09-30,2022-05-20
3,NOR19820921,69163,quincieux,ICB,inondations et/ou coulees de boue,1982-08-16,1982-08-16,1982-09-21,1982-09-30,2022-05-20
4,NOR19820921,69122,lucenay,ICB,inondations et/ou coulees de boue,1982-08-16,1982-08-16,1982-09-21,1982-09-30,2022-05-20

In [3]:
# Compter les arrêtés et les communes pour chaque type de risque
risques = client.query("""
    SELECT
        lib_risque_jo,
        COUNT(*) AS nb_arretes,
        COUNT(DISTINCT code_commune) AS nb_communes
    FROM `wagon-bootcamp-501621.staging.catnat_staging`
    GROUP BY lib_risque_jo
    ORDER BY nb_arretes DESC
""").to_dataframe()
risques

/Users/asmaammouri/code/Asma-Iam/hydraxai-france/.venv/lib/python3.12/site-packages/google/cloud/bigquery/table.py:2128: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

                                  lib_risque_jo  nb_arretes  nb_communes
0             inondations et/ou coulees de boue      139419        34578
1                                    secheresse       43417        14222
2                          mouvement de terrain       31711        27437
3                                       tempete       16025        14915
4   chocs mecaniques lies a l'action des vagues        6720         4309
5                         glissement de terrain        3182         2699
6                             poids de la neige        2758         2758
7                    inondations remontee nappe        1368         1152
8                                         grele        1333         1263
9                             secousse sismique         749          682
10                                    avalanche         119           73
11               effondrement et/ou affaisement         105           93
12                            vents cycloniques          85           83
13                                       divers          65           65
14              eboulement et/ou chute de blocs          63           56
15                                 raz de maree           6            6
16                            lave torrentielle           6            6
17                               coulee de boue           4            4
18        glissement et effondrement de terrain           3            3
19             glissement et eboulement rocheux           1            1
20                          eruption volcanique           1            1